import { NextResponse } from 'next/server';
import { webMCPTools } from '@/lib/webmcp/tools';

export async function GET() {
  return NextResponse.json({
    protocol: 'WebMCP',
    standard: 'document.modelContext.registerTool',
    version: '1.0.0',
    description: 'Netify WebMCP Browser Agent Tools for African Trade Receivables',
    toolsCount: webMCPTools.length,
    httpExecutionUrl: 'https://app.netify.ng/api/webmcp/execute?tool={tool_name}',
    quickExecutionExamples: {
      getCollectionPriority: 'https://app.netify.ng/api/webmcp/execute?tool=get_collection_priority&limit=5',
      searchCustomers: 'https://app.netify.ng/api/webmcp/execute?tool=search_customers&query=ABC',
      getCustomerEvidence: 'https://app.netify.ng/api/webmcp/execute?tool=get_customer_evidence&customerId=f14e802a-573d-46bb-8257-317bdc3cddb0',
      listReceivables: 'https://app.netify.ng/api/webmcp/execute?tool=list_receivables',
    },
    liveTopOverdueDebtorsPreview: [
      {
        rank: 1,
        customerId: 'f14e802a-573d-46bb-8257-317bdc3cddb0',
        customerName: 'ABC Stores',
        totalOutstanding: '₦850,000',
        oldestOverdueDays: 21,
        priorityScore: 75,
        urgency: 'HIGH',
        reasons: ['NGN 850,000 overdue', '21 days overdue', 'Missed 1 payment commitment', 'No confirmed payments on record'],
      },
      {
        rank: 2,
        customerId: '7e8093e8-ce07-4d20-8628-0b6ad59286a2',
        customerName: 'Northern Distribution',
        totalOutstanding: '₦1,200,000',
        oldestOverdueDays: 36,
        priorityScore: 66,
        urgency: 'MEDIUM',
        reasons: ['NGN 1,200,000 overdue', '36 days overdue', 'Missed 1 payment commitment'],
      },
      {
        rank: 3,
        customerId: 'e86a8453-e1c2-4526-92a1-42b3d31c125f',
        customerName: 'Musa Enterprises',
        totalOutstanding: '₦450,000',
        oldestOverdueDays: 0,
        priorityScore: 66,
        urgency: 'MEDIUM',
        reasons: ['NGN 450,000 overdue', 'Commitment due today', 'No confirmed payments on record'],
      },
    ],
    tools: webMCPTools.map((t) => ({
      name: t.name,
      description: t.description,
      category: t.category,
      inputSchema: t.inputSchema,
      executeEndpoint: `https://app.netify.ng/api/webmcp/execute?tool=${t.name}`,
    })),
    documentationUrl: 'https://app.netify.ng/webmcp',
    authorization: {
      type: 'oauth2',
      standard: 'RFC 7636 (PKCE) + RFC 6749',
      authorizationEndpoint: 'https://app.netify.ng/oauth/authorize',
      tokenEndpoint: 'https://app.netify.ng/api/oauth/token',
      revocationEndpoint: 'https://app.netify.ng/api/oauth/revoke',
      grantsEndpoint: 'https://app.netify.ng/api/oauth/grants',
      supportedResponseTypes: ['code'],
      supportedCodeChallengeMethods: ['S256', 'plain'],
      supportedScopes: [
        'receivables:read',
        'customers:read',
        'customer_evidence:read',
        'customer_risk:read',
        'business_memory:read',
        'notifications:read',
        'collection_messages:draft',
        'payment_commitments:write',
        'collection_activity:write',
        'notifications:write',
      ],
    },
    judgeCredentials: {
      url: 'https://app.netify.ng/login',
      email: 'merchant@netify.ng',
      password: 'Password123!',
    },
  });
}
