import { renderBaseEmailTemplate } from './base.template';

export function renderPasswordChangedEmail({
  firstName,
  timestamp,
  ipAddress,
}: {
  firstName: string;
  timestamp: string;
  ipAddress?: string;
}): {
  subject: string;
  html: string;
  text: string;
} {
  const subject = `Security Alert: Your Netify password was changed`;

  const bodyContent = `
    <p>Hello <strong>${firstName}</strong>,</p>
    <p>This is a confirmation that the password for your <strong>Netify</strong> account was successfully changed on <strong>${timestamp}</strong>.</p>
    ${
      ipAddress
        ? `<p style="font-size: 13px; color: #94a3b8;">Requested from IP address: <code>${ipAddress}</code></p>`
        : ''
    }
    <div style="background-color: #1e293b; border-left: 4px solid #ef4444; padding: 16px; border-radius: 8px; margin: 24px 0;">
      <p style="margin: 0; color: #f8fafc; font-size: 14px;">
        <strong>Didn't make this change?</strong>
      </p>
      <p style="margin: 6px 0 0 0; color: #cbd5e1; font-size: 13px;">
        If you did not initiate this change, your account may be compromised. Please reset your password immediately using the mobile app or contact support.
      </p>
    </div>
  `;

  const html = renderBaseEmailTemplate({
    previewText: 'Your Netify account password was changed.',
    heading: 'Password Changed Successfully',
    bodyContent,
    footerNote: 'This security notification was automatically generated by Netify.',
  });

  const text = `Hello ${firstName},\n\nYour Netify password was changed on ${timestamp}.\n\nIf you did not make this change, please reset your password immediately.\n\nBest regards,\nThe Netify Security Team`;

  return { subject, html, text };
}
