import { renderBaseEmailTemplate } from './base.template';

export function renderPasswordChangedEmail({
  firstName,
  timestamp,
  ipAddress,
}: {
  firstName: string;
  timestamp: string;
  ipAddress?: string;
}): {
  subject: string;
  html: string;
  text: string;
} {
  const subject = `Security Alert: Your Netify password was changed`;

  const bodyContent = `
    <div style="margin-bottom: 16px;">
      <span style="background: rgba(239, 68, 68, 0.15); border: 1px solid rgba(239, 68, 68, 0.4); color: #EF4444; padding: 3px 10px; border-radius: 20px; font-size: 11.5px; font-weight: 700;">
        &#128680; Security Notice
      </span>
    </div>

    <p style="margin: 0 0 14px 0;">Hello <strong>${firstName}</strong>,</p>
    <p style="margin: 0 0 20px 0; color: #CBD5E1;">
      This is a confirmation that the password for your <strong>Netify</strong> account was successfully changed.
    </p>

    <div style="background-color: #00253E; border: 1px solid #0B3C5D; border-radius: 10px; padding: 16px; margin: 20px 0;">
      <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
          <td style="color: #94A3B8; font-size: 12.5px; padding-bottom: 6px;"><strong>Change Timestamp:</strong></td>
          <td style="color: #F8FAFC; font-size: 12.5px; padding-bottom: 6px; text-align: right;">${timestamp}</td>
        </tr>
        ${
          ipAddress
            ? `
        <tr>
          <td style="color: #94A3B8; font-size: 12.5px;"><strong>IP Address:</strong></td>
          <td style="color: #00A581; font-size: 12.5px; font-family: monospace; text-align: right;">${ipAddress}</td>
        </tr>
        `
            : ''
        }
      </table>
    </div>

    <div style="background-color: rgba(239, 68, 68, 0.1); border-left: 4px solid #EF4444; padding: 16px; border-radius: 8px; margin: 24px 0;">
      <p style="margin: 0; color: #FFFFFF; font-size: 13.5px; font-weight: 700;">
        Didn't make this change?
      </p>
      <p style="margin: 6px 0 0 0; color: #CBD5E1; font-size: 12.5px; line-height: 1.5;">
        If you did not authorize this password update, your account may be compromised. Please reset your password immediately or contact support.
      </p>
    </div>

    <div style="text-align: center; margin: 24px 0;">
      <a href="https://app.netify.africa/forgot-password" class="btn" style="background-color: #EF4444; color: #FFFFFF; font-weight: 700; text-decoration: none; padding: 12px 24px; border-radius: 8px; display: inline-block; font-size: 14px;">
        Secure Account & Reset Password &rarr;
      </a>
    </div>
  `;

  const html = renderBaseEmailTemplate({
    previewText: 'Your Netify account password was successfully updated.',
    heading: 'Password Changed Successfully',
    bodyContent,
    footerNote: 'This security notification was automatically generated by Netify Security.',
  });

  const text = `Hello ${firstName},\n\nYour Netify password was changed on ${timestamp}.\n\nIf you did not make this change, please secure your account immediately: https://app.netify.africa/forgot-password\n\nBest regards,\nThe Netify Security Team`;

  return { subject, html, text };
}
