export enum UserRole {
  OWNER = 'OWNER',
  MEMBER = 'MEMBER',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  STAFF = 'STAFF',
}

export enum OrganizationStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  ARCHIVED = 'ARCHIVED',
}

export enum MembershipStatus {
  ACTIVE = 'ACTIVE',
  INVITED = 'INVITED',
  SUSPENDED = 'SUSPENDED',
  REMOVED = 'REMOVED',
}

export enum CustomerStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ARCHIVED = 'ARCHIVED',
  BLOCKED = 'BLOCKED',
}

export enum ContactType {
  PHONE = 'PHONE',
  EMAIL = 'EMAIL',
  WHATSAPP = 'WHATSAPP',
  OTHER = 'OTHER',
}

export enum ReceivableSource {
  MANUAL = 'MANUAL',
  INVOICE = 'INVOICE',
  CREDIT_SALE = 'CREDIT_SALE',
  OTHER = 'OTHER',
}

export enum ReceivableStatus {
  OPEN = 'OPEN',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  DISPUTED = 'DISPUTED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  FAILED = 'FAILED',
  REVERSED = 'REVERSED',
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  ISSUED = 'ISSUED',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMethod {
  CASH = 'CASH',
  BANK_TRANSFER = 'BANK_TRANSFER',
  MOBILE_MONEY = 'MOBILE_MONEY',
  CARD = 'CARD',
  POS = 'POS',
  OTHER = 'OTHER',
}

export enum TransactionType {
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
}

export enum ActivityType {
  CALL = 'CALL',
  WHATSAPP = 'WHATSAPP',
  SMS = 'SMS',
  EMAIL = 'EMAIL',
  IN_PERSON = 'IN_PERSON',
  PAYMENT_REMINDER = 'PAYMENT_REMINDER',
  FOLLOW_UP = 'FOLLOW_UP',
  OTHER = 'OTHER',
}

export enum CollectionChannel {
  PHONE = 'PHONE',
  WHATSAPP = 'WHATSAPP',
  SMS = 'SMS',
  EMAIL = 'EMAIL',
  IN_PERSON = 'IN_PERSON',
  OTHER = 'OTHER',
}

export enum ActivityOutcome {
  NO_RESPONSE = 'NO_RESPONSE',
  CONTACTED = 'CONTACTED',
  PROMISED_PAYMENT = 'PROMISED_PAYMENT',
  PARTIAL_PAYMENT = 'PARTIAL_PAYMENT',
  FULL_PAYMENT = 'FULL_PAYMENT',
  DISPUTE = 'DISPUTE',
  REQUESTED_EXTENSION = 'REQUESTED_EXTENSION',
  WRONG_CONTACT = 'WRONG_CONTACT',
  CUSTOMER_UNAVAILABLE = 'CUSTOMER_UNAVAILABLE',
  OTHER = 'OTHER',
}

export enum CommitmentStatus {
  PENDING = 'PENDING',
  FULFILLED = 'FULFILLED',
  MISSED = 'MISSED',
  CANCELLED = 'CANCELLED',
  PARTIALLY_FULFILLED = 'PARTIALLY_FULFILLED',
}

export enum CommitmentSource {
  MANUAL = 'MANUAL',
  CONVERSATION = 'CONVERSATION',
  DOCUMENT = 'DOCUMENT',
  AI_EXTRACTION = 'AI_EXTRACTION',
}

export enum ConfidenceLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum CollectionPriorityCategory {
  DUE_TODAY = 'DUE_TODAY',
  DUE_SOON = 'DUE_SOON',
  OVERDUE = 'OVERDUE',
  MISSED_COMMITMENT = 'MISSED_COMMITMENT',
  HIGH_RISK = 'HIGH_RISK',
  NEEDS_FOLLOW_UP = 'NEEDS_FOLLOW_UP',
}

export enum CommunicationChannel {
  WHATSAPP = 'WHATSAPP',
  SMS = 'SMS',
  CALL_NOTE = 'CALL_NOTE',
  EMAIL = 'EMAIL',
  IN_PERSON = 'IN_PERSON',
}

export enum MessageSenderType {
  BUSINESS = 'BUSINESS',
  CUSTOMER = 'CUSTOMER',
  SYSTEM = 'SYSTEM',
}

export enum DocumentType {
  INVOICE = 'INVOICE',
  RECEIPT = 'RECEIPT',
  STATEMENT = 'STATEMENT',
  CONTRACT = 'CONTRACT',
  OTHER = 'OTHER',
}

export enum DocumentStatus {
  UPLOADED = 'UPLOADED',
  PROCESSING = 'PROCESSING',
  EXTRACTED = 'EXTRACTED',
  FAILED = 'FAILED',
}

export enum BusinessEventType {
  CUSTOMER_CREATED = 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED = 'CUSTOMER_UPDATED',
  INVOICE_CREATED = 'INVOICE_CREATED',
  INVOICE_OVERDUE = 'INVOICE_OVERDUE',
  INVOICE_PAID = 'INVOICE_PAID',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_MISSED = 'PAYMENT_MISSED',
  COMMITMENT_CREATED = 'COMMITMENT_CREATED',
  COMMITMENT_MISSED = 'COMMITMENT_MISSED',
  COMMITMENT_FULFILLED = 'COMMITMENT_FULFILLED',
  CUSTOMER_CONTACTED = 'CUSTOMER_CONTACTED',
  CUSTOMER_REQUESTED_EXTENSION = 'CUSTOMER_REQUESTED_EXTENSION',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  RISK_EVALUATED = 'RISK_EVALUATED',
}

export enum AIActionType {
  FOLLOW_UP_CALL = 'FOLLOW_UP_CALL',
  SEND_PAYMENT_REMINDER = 'SEND_PAYMENT_REMINDER',
  OFFER_PAYMENT_PLAN = 'OFFER_PAYMENT_PLAN',
  ESCALATE = 'ESCALATE',
  RECONCILE = 'RECONCILE',
}

export enum AIActionStatus {
  SUGGESTED = 'SUGGESTED',
  ACCEPTED = 'ACCEPTED',
  DISMISSED = 'DISMISSED',
  EXECUTED = 'EXECUTED',
}

export enum SubscriptionPlan {
  FREE = 'FREE',
  PRO = 'PRO',
}

export enum SubscriptionStatus {
  ACTIVE = 'ACTIVE',
  TRIALING = 'TRIALING',
  PAST_DUE = 'PAST_DUE',
  CANCELED = 'CANCELED',
  EXPIRED = 'EXPIRED',
}
